branches:
  only:
    - master

only_commits:
  files:
    - src/
  
max_jobs: 1

image: Visual Studio 2017

clone_folder: c:\projects\nybus

environment:
  COVERALLS_REPO_TOKEN:
    secure: FLG2WTxc1Gvrikrvj/UXnb9IAklUhPKGYV5pxOzlwsOWGQBiiEigRnyWCvCc2Zga  

cache:
  - '%LocalAppData%\NuGet\v3-cache'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet tool install -g Cake.Tool --version 0.30.0
  - cmd: dotnet tool install coveralls.net --tool-path tools

build_script:
  - cmd: dotnet cake --target=Full

after_build:
  - ps: .\tools\csmacnz.coveralls.exe --reportgenerator -i .\outputs\tests\report --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID